### ISSUE TITLE
Missing template for '$ generate_deployment_manifest warden'

### ISSUE THREAD

**Issue by mgarciap** [cloudfoundry-community-attic/cf-services-release#24]
Script usage:

```
$ ./generate_deployment_manifest 
usage: ./generate_deployment_manifest <aws|warden|vsphere>
```

```
$ ./generate_deployment_manifest warden
2013/11/11 23:06:45 error reading stub: open ./templates/cf-infrastructure-warden.yml: no such file or directory
```

 Available templates:

```
$ ls templates/cf-infrastructure-*
templates/cf-infrastructure-aws.yml templates/cf-infrastructure-vsphere.yml
```

**Comment by ruthie** [comment]
Hi,

Unfortunately, cf-services-release doesn't support being run against bosh-lite/warden.  We're not sure how difficult adding this functionality would be.  It may be as easy as adding the infrastructure file, which you can find in cf-release (https://github.com/cloudfoundry/cf-release/blob/master/templates/cf-infrastructure-warden.yml).  If you get it working, we'd be happy to accept a pull request.  

In the mean time, we're removing the warden option from the script because it's deceptive.

Best,

@ruthie @charliebevis
